trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_TAG: $(Build.SourceVersion)
  IMAGE_NAME: 'samples/test'

steps:
  - task: AzureContainerApps@1
    inputs:
      appSourcePath: '$(Build.SourcesDirectory)'
      azureSubscription: 'abdul-test-service-connection'
      acrName: 'abdultest20oct2025'
      containerAppName: 'abdultestca'
      resourceGroup: 'abdultestRG'
      containerImage: '$(IMAGE_NAME):$(IMAGE_TAG)'